package main

type SeedAuthor struct {
	Name        string
	Biography   string
	BirthDate   string
	Nationality string
	Books       []SeedBook
}

type SeedBook struct {
	Title         string
	PublishedYear int
	Pages         int
	Language      string
	Genre         string
	Publisher     string
	Description   string
}

var seedAuthors = []SeedAuthor{
	{
		Name:        "Fyodor Dostoevsky",
		Biography:   "Russian novelist and philosopher whose works probe the depths of human psychology and moral conflict.",
		BirthDate:   "1821-11-11",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "Crime and Punishment",
				PublishedYear: 1866,
				Pages:         671,
				Language:      "English",
				Genre:         "Psychological Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "An impoverished ex-student commits murder and is tormented by guilt and the search for redemption.",
			},
			{
				Title:         "The Brothers Karamazov",
				PublishedYear: 1880,
				Pages:         796,
				Language:      "English",
				Genre:         "Philosophical Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "A passionate philosophical novel of patricide, faith, doubt and reason among three brothers.",
			},
			{
				Title:         "The Idiot",
				PublishedYear: 1869,
				Pages:         656,
				Language:      "English",
				Genre:         "Classic Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "A pure-hearted prince returns to Russian society and is destroyed by the people he tries to save.",
			},
			{
				Title:         "Notes from Underground",
				PublishedYear: 1864,
				Pages:         136,
				Language:      "English",
				Genre:         "Existentialist Fiction",
				Publisher:     "Epoch",
				Description:   "The bitter monologue of an isolated civil servant in 19th-century St. Petersburg.",
			},
			{
				Title:         "Demons",
				PublishedYear: 1872,
				Pages:         768,
				Language:      "English",
				Genre:         "Political Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "A small Russian town slides into chaos under the spell of nihilist revolutionaries.",
			},
		},
	},
	{
		Name:        "Leo Tolstoy",
		Biography:   "Russian writer regarded as one of the greatest authors of all time, known for his sweeping realist novels.",
		BirthDate:   "1828-09-09",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "War and Peace",
				PublishedYear: 1869,
				Pages:         1225,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "Five aristocratic families navigate love, war and history during the Napoleonic invasion of Russia.",
			},
			{
				Title:         "Anna Karenina",
				PublishedYear: 1877,
				Pages:         864,
				Language:      "English",
				Genre:         "Realist Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "A married aristocrat's affair with a young officer unravels her life in Imperial Russia.",
			},
			{
				Title:         "The Death of Ivan Ilyich",
				PublishedYear: 1886,
				Pages:         96,
				Language:      "English",
				Genre:         "Novella",
				Publisher:     "Stepan Petrovich Yakovlev",
				Description:   "A high-court judge confronts the meaning of his life as he faces a terminal illness.",
			},
		},
	},
	{
		Name:        "Jane Austen",
		Biography:   "English novelist whose social commentary and irony made her one of the most widely read writers in English literature.",
		BirthDate:   "1775-12-16",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Pride and Prejudice",
				PublishedYear: 1813,
				Pages:         432,
				Language:      "English",
				Genre:         "Romance",
				Publisher:     "T. Egerton, Whitehall",
				Description:   "Elizabeth Bennet learns the dangers of first impressions in her sparring with the proud Mr. Darcy.",
			},
			{
				Title:         "Sense and Sensibility",
				PublishedYear: 1811,
				Pages:         409,
				Language:      "English",
				Genre:         "Romance",
				Publisher:     "T. Egerton, Whitehall",
				Description:   "Two sisters navigate love and inheritance in Regency England with very different temperaments.",
			},
			{
				Title:         "Emma",
				PublishedYear: 1815,
				Pages:         474,
				Language:      "English",
				Genre:         "Romance",
				Publisher:     "John Murray",
				Description:   "A clever, well-meaning young woman meddles in the romantic lives of those around her.",
			},
			{
				Title:         "Persuasion",
				PublishedYear: 1817,
				Pages:         256,
				Language:      "English",
				Genre:         "Romance",
				Publisher:     "John Murray",
				Description:   "Anne Elliot is given a second chance with the man she was once persuaded to refuse.",
			},
		},
	},
	{
		Name:        "Charles Dickens",
		Biography:   "English writer and social critic whose vivid characters and indictments of Victorian society made him the most popular novelist of his era.",
		BirthDate:   "1812-02-07",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Great Expectations",
				PublishedYear: 1861,
				Pages:         544,
				Language:      "English",
				Genre:         "Bildungsroman",
				Publisher:     "Chapman & Hall",
				Description:   "An orphan named Pip rises through Victorian society in pursuit of fortune and a cold-hearted love.",
			},
			{
				Title:         "A Tale of Two Cities",
				PublishedYear: 1859,
				Pages:         489,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "Chapman & Hall",
				Description:   "Love and sacrifice intertwine in London and Paris during the upheaval of the French Revolution.",
			},
			{
				Title:         "Oliver Twist",
				PublishedYear: 1838,
				Pages:         608,
				Language:      "English",
				Genre:         "Social Fiction",
				Publisher:     "Richard Bentley",
				Description:   "An orphan flees to London and falls in with a gang of pickpockets led by the sinister Fagin.",
			},
			{
				Title:         "David Copperfield",
				PublishedYear: 1850,
				Pages:         882,
				Language:      "English",
				Genre:         "Bildungsroman",
				Publisher:     "Bradbury & Evans",
				Description:   "A semi-autobiographical account of a young man's coming-of-age in Victorian England.",
			},
			{
				Title:         "Bleak House",
				PublishedYear: 1853,
				Pages:         1017,
				Language:      "English",
				Genre:         "Social Fiction",
				Publisher:     "Bradbury & Evans",
				Description:   "A lawsuit drags on for generations as Dickens skewers the Victorian Court of Chancery.",
			},
		},
	},
	{
		Name:        "Mark Twain",
		Biography:   "American writer and humorist celebrated for his vivid portrayals of life along the Mississippi River.",
		BirthDate:   "1835-11-30",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Adventures of Huckleberry Finn",
				PublishedYear: 1884,
				Pages:         366,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Chatto & Windus",
				Description:   "Huck and the runaway slave Jim raft down the Mississippi in search of freedom.",
			},
			{
				Title:         "The Adventures of Tom Sawyer",
				PublishedYear: 1876,
				Pages:         274,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "American Publishing Company",
				Description:   "A mischievous boy's escapades in a sleepy Missouri town along the Mississippi River.",
			},
			{
				Title:         "A Connecticut Yankee in King Arthur's Court",
				PublishedYear: 1889,
				Pages:         450,
				Language:      "English",
				Genre:         "Satire",
				Publisher:     "Charles L. Webster & Co.",
				Description:   "A 19th-century engineer is transported to medieval England and tries to modernize Camelot.",
			},
		},
	},
	{
		Name:        "Herman Melville",
		Biography:   "American novelist and poet whose later works were largely unrecognized in his lifetime.",
		BirthDate:   "1819-08-01",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "Moby-Dick",
				PublishedYear: 1851,
				Pages:         635,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Harper & Brothers",
				Description:   "Captain Ahab pursues the white whale that took his leg in a doomed voyage of obsession.",
			},
			{
				Title:         "Billy Budd",
				PublishedYear: 1924,
				Pages:         128,
				Language:      "English",
				Genre:         "Novella",
				Publisher:     "Constable & Co.",
				Description:   "A handsome young sailor's tragic encounter with envy and military justice at sea.",
			},
		},
	},
	{
		Name:        "F. Scott Fitzgerald",
		Biography:   "American novelist and short-story writer who chronicled the Jazz Age and its disillusionments.",
		BirthDate:   "1896-09-24",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Great Gatsby",
				PublishedYear: 1925,
				Pages:         180,
				Language:      "English",
				Genre:         "Tragedy",
				Publisher:     "Charles Scribner's Sons",
				Description:   "A mysterious millionaire's pursuit of a lost love exposes the hollowness of the American Dream.",
			},
			{
				Title:         "Tender Is the Night",
				PublishedYear: 1934,
				Pages:         317,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "Charles Scribner's Sons",
				Description:   "An American psychiatrist on the French Riviera unravels alongside his glamorous wife.",
			},
		},
	},
	{
		Name:        "Ernest Hemingway",
		Biography:   "American novelist, short-story writer, and journalist whose spare prose shaped 20th-century fiction.",
		BirthDate:   "1899-07-21",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Old Man and the Sea",
				PublishedYear: 1952,
				Pages:         127,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "Charles Scribner's Sons",
				Description:   "An aging Cuban fisherman hooks a giant marlin and battles it across the Gulf Stream.",
			},
			{
				Title:         "A Farewell to Arms",
				PublishedYear: 1929,
				Pages:         332,
				Language:      "English",
				Genre:         "War Fiction",
				Publisher:     "Charles Scribner's Sons",
				Description:   "An American ambulance driver in World War I Italy falls for a British nurse.",
			},
			{
				Title:         "For Whom the Bell Tolls",
				PublishedYear: 1940,
				Pages:         471,
				Language:      "English",
				Genre:         "War Fiction",
				Publisher:     "Charles Scribner's Sons",
				Description:   "An American dynamiter joins a guerrilla band behind enemy lines during the Spanish Civil War.",
			},
		},
	},
	{
		Name:        "Virginia Woolf",
		Biography:   "English modernist writer whose stream-of-consciousness novels reshaped 20th-century fiction.",
		BirthDate:   "1882-01-25",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Mrs Dalloway",
				PublishedYear: 1925,
				Pages:         194,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Hogarth Press",
				Description:   "A single day in post-war London follows Clarissa Dalloway and a shell-shocked veteran.",
			},
			{
				Title:         "To the Lighthouse",
				PublishedYear: 1927,
				Pages:         209,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Hogarth Press",
				Description:   "The Ramsay family's visits to a Scottish island span years of love, loss and time.",
			},
			{
				Title:         "Orlando",
				PublishedYear: 1928,
				Pages:         333,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Hogarth Press",
				Description:   "A young nobleman lives for centuries and changes sex, surveying English literature along the way.",
			},
		},
	},
	{
		Name:        "James Joyce",
		Biography:   "Irish novelist and poet considered one of the most influential writers of the modernist avant-garde.",
		BirthDate:   "1882-02-02",
		Nationality: "Irish",
		Books: []SeedBook{
			{
				Title:         "Ulysses",
				PublishedYear: 1922,
				Pages:         730,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Sylvia Beach",
				Description:   "A single day in Dublin retraces the wanderings of Homer's Odyssey through Leopold Bloom.",
			},
			{
				Title:         "Dubliners",
				PublishedYear: 1914,
				Pages:         225,
				Language:      "English",
				Genre:         "Short Stories",
				Publisher:     "Grant Richards Ltd.",
				Description:   "Fifteen stories of paralysis, longing and small revelations in early-20th-century Dublin.",
			},
			{
				Title:         "A Portrait of the Artist as a Young Man",
				PublishedYear: 1916,
				Pages:         329,
				Language:      "English",
				Genre:         "Bildungsroman",
				Publisher:     "B. W. Huebsch",
				Description:   "Stephen Dedalus rejects family, country and church to become an artist.",
			},
		},
	},
	{
		Name:        "George Orwell",
		Biography:   "English novelist, essayist, and critic best known for his fierce opposition to totalitarianism.",
		BirthDate:   "1903-06-25",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "1984",
				PublishedYear: 1949,
				Pages:         328,
				Language:      "English",
				Genre:         "Dystopian Fiction",
				Publisher:     "Secker & Warburg",
				Description:   "Winston Smith rebels against Big Brother in a society of total surveillance and thought control.",
			},
			{
				Title:         "Animal Farm",
				PublishedYear: 1945,
				Pages:         112,
				Language:      "English",
				Genre:         "Political Satire",
				Publisher:     "Secker & Warburg",
				Description:   "Farm animals overthrow their human master only to fall under a worse tyranny of pigs.",
			},
		},
	},
	{
		Name:        "Aldous Huxley",
		Biography:   "English writer and philosopher whose works examine the dehumanizing aspects of scientific progress.",
		BirthDate:   "1894-07-26",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Brave New World",
				PublishedYear: 1932,
				Pages:         311,
				Language:      "English",
				Genre:         "Dystopian Fiction",
				Publisher:     "Chatto & Windus",
				Description:   "A future society engineered for happiness through genetics, conditioning and the drug soma.",
			},
		},
	},
	{
		Name:        "Franz Kafka",
		Biography:   "German-language novelist whose surreal fiction blends realism with the fantastical and absurd.",
		BirthDate:   "1883-07-03",
		Nationality: "Austro-Hungarian",
		Books: []SeedBook{
			{
				Title:         "The Trial",
				PublishedYear: 1925,
				Pages:         255,
				Language:      "English",
				Genre:         "Absurdist Fiction",
				Publisher:     "Verlag Die Schmiede",
				Description:   "Josef K. is arrested by an unknown court for an unknown crime he never learns of.",
			},
			{
				Title:         "The Metamorphosis",
				PublishedYear: 1915,
				Pages:         96,
				Language:      "English",
				Genre:         "Absurdist Fiction",
				Publisher:     "Kurt Wolff Verlag",
				Description:   "A traveling salesman wakes one morning transformed into a giant insect.",
			},
			{
				Title:         "The Castle",
				PublishedYear: 1926,
				Pages:         328,
				Language:      "English",
				Genre:         "Absurdist Fiction",
				Publisher:     "Kurt Wolff Verlag",
				Description:   "A land-surveyor struggles to gain access to a remote castle's mysterious authorities.",
			},
		},
	},
	{
		Name:        "Albert Camus",
		Biography:   "French philosopher, author, and journalist whose work expressed the absurdity of the human condition.",
		BirthDate:   "1913-11-07",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "The Stranger",
				PublishedYear: 1942,
				Pages:         123,
				Language:      "English",
				Genre:         "Existentialist Fiction",
				Publisher:     "Gallimard",
				Description:   "Meursault, an indifferent French Algerian, kills a man and is tried for failing to mourn his mother.",
			},
			{
				Title:         "The Plague",
				PublishedYear: 1947,
				Pages:         308,
				Language:      "English",
				Genre:         "Existentialist Fiction",
				Publisher:     "Gallimard",
				Description:   "An Algerian city is sealed off as the bubonic plague tests the city's doctors and residents.",
			},
			{
				Title:         "The Fall",
				PublishedYear: 1956,
				Pages:         147,
				Language:      "English",
				Genre:         "Philosophical Fiction",
				Publisher:     "Gallimard",
				Description:   "A former Parisian lawyer confesses to a stranger in an Amsterdam bar.",
			},
		},
	},
	{
		Name:        "Gabriel García Márquez",
		Biography:   "Colombian novelist and Nobel laureate, a leading figure of Latin American magical realism.",
		BirthDate:   "1927-03-06",
		Nationality: "Colombian",
		Books: []SeedBook{
			{
				Title:         "One Hundred Years of Solitude",
				PublishedYear: 1967,
				Pages:         417,
				Language:      "English",
				Genre:         "Magical Realism",
				Publisher:     "Editorial Sudamericana",
				Description:   "Seven generations of the Buendía family rise and fall in the mythic town of Macondo.",
			},
			{
				Title:         "Love in the Time of Cholera",
				PublishedYear: 1985,
				Pages:         348,
				Language:      "English",
				Genre:         "Magical Realism",
				Publisher:     "Editorial Oveja Negra",
				Description:   "A man waits half a century for the woman he loved in his youth.",
			},
		},
	},
	{
		Name:        "Jorge Luis Borges",
		Biography:   "Argentine writer whose short stories and essays helped define Latin American literature.",
		BirthDate:   "1899-08-24",
		Nationality: "Argentine",
		Books: []SeedBook{
			{
				Title:         "Ficciones",
				PublishedYear: 1944,
				Pages:         174,
				Language:      "English",
				Genre:         "Short Stories",
				Publisher:     "Editorial Sur",
				Description:   "Labyrinthine short stories about libraries, mirrors, infinite books and unreal worlds.",
			},
		},
	},
	{
		Name:        "Miguel de Cervantes",
		Biography:   "Spanish writer widely regarded as the greatest in the Spanish language and the father of the modern novel.",
		BirthDate:   "1547-09-29",
		Nationality: "Spanish",
		Books: []SeedBook{
			{
				Title:         "Don Quixote",
				PublishedYear: 1605,
				Pages:         982,
				Language:      "English",
				Genre:         "Satire",
				Publisher:     "Francisco de Robles",
				Description:   "An aging gentleman becomes obsessed with chivalric romances and sets off as a knight-errant.",
			},
		},
	},
	{
		Name:        "Victor Hugo",
		Biography:   "French Romantic writer whose novels championed the marginalized and the struggle for justice.",
		BirthDate:   "1802-02-26",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "Les Misérables",
				PublishedYear: 1862,
				Pages:         1463,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "A. Lacroix, Verboeckhoven & Cie",
				Description:   "Ex-convict Jean Valjean seeks redemption while pursued by the relentless Inspector Javert.",
			},
			{
				Title:         "The Hunchback of Notre-Dame",
				PublishedYear: 1831,
				Pages:         512,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Charles Gosselin",
				Description:   "The deformed bell-ringer Quasimodo loves the gypsy Esmeralda in 15th-century Paris.",
			},
		},
	},
	{
		Name:        "Alexandre Dumas",
		Biography:   "French novelist whose adventure stories made him one of the most widely read French authors.",
		BirthDate:   "1802-07-24",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "The Count of Monte Cristo",
				PublishedYear: 1844,
				Pages:         1276,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Pétion",
				Description:   "Wrongly imprisoned Edmond Dantès escapes and patiently engineers revenge on his betrayers.",
			},
			{
				Title:         "The Three Musketeers",
				PublishedYear: 1844,
				Pages:         700,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Baudry",
				Description:   "Young d'Artagnan joins three royal musketeers in adventures and intrigues at the French court.",
			},
		},
	},
	{
		Name:        "Gustave Flaubert",
		Biography:   "French novelist whose meticulous prose style was a foundation of literary realism.",
		BirthDate:   "1821-12-12",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "Madame Bovary",
				PublishedYear: 1856,
				Pages:         329,
				Language:      "English",
				Genre:         "Realist Fiction",
				Publisher:     "Revue de Paris",
				Description:   "A provincial doctor's wife seeks escape from her dull marriage through affairs and debt.",
			},
			{
				Title:         "Sentimental Education",
				PublishedYear: 1869,
				Pages:         464,
				Language:      "English",
				Genre:         "Realist Fiction",
				Publisher:     "Michel Lévy frères",
				Description:   "A young man from the provinces drifts through Paris, love and the 1848 revolution.",
			},
		},
	},
	{
		Name:        "Émile Zola",
		Biography:   "French novelist and the leading practitioner of literary naturalism.",
		BirthDate:   "1840-04-02",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "Germinal",
				PublishedYear: 1885,
				Pages:         591,
				Language:      "English",
				Genre:         "Naturalist Fiction",
				Publisher:     "Charpentier",
				Description:   "Coal miners in northern France strike against unbearable conditions in the 1860s.",
			},
			{
				Title:         "Thérèse Raquin",
				PublishedYear: 1867,
				Pages:         233,
				Language:      "English",
				Genre:         "Naturalist Fiction",
				Publisher:     "Albert Lacroix",
				Description:   "A passionate affair leads to murder and is consumed by guilt in 19th-century Paris.",
			},
		},
	},
	{
		Name:        "Marcel Proust",
		Biography:   "French novelist whose vast novel In Search of Lost Time is a landmark of modernist literature.",
		BirthDate:   "1871-07-10",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "Swann's Way",
				PublishedYear: 1913,
				Pages:         444,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Grasset",
				Description:   "Memory, love and time unfold from the taste of a madeleine dipped in tea.",
			},
		},
	},
	{
		Name:        "Nikolai Gogol",
		Biography:   "Russian novelist and dramatist of Ukrainian origin, a master of the absurd and grotesque.",
		BirthDate:   "1809-03-31",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "Dead Souls",
				PublishedYear: 1842,
				Pages:         464,
				Language:      "English",
				Genre:         "Satire",
				Publisher:     "Moscow University Press",
				Description:   "A schemer travels rural Russia buying the names of dead serfs to inflate his social standing.",
			},
			{
				Title:         "The Overcoat",
				PublishedYear: 1842,
				Pages:         96,
				Language:      "English",
				Genre:         "Short Story",
				Publisher:     "Sovremennik",
				Description:   "A meek St. Petersburg clerk's life turns on the loss of his prized new overcoat.",
			},
		},
	},
	{
		Name:        "Ivan Turgenev",
		Biography:   "Russian novelist, short-story writer and playwright whose realism shaped Russian literary tradition.",
		BirthDate:   "1818-11-09",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "Fathers and Sons",
				PublishedYear: 1862,
				Pages:         226,
				Language:      "English",
				Genre:         "Realist Fiction",
				Publisher:     "The Russian Messenger",
				Description:   "Two generations clash over love, science and politics in mid-19th-century Russia.",
			},
		},
	},
	{
		Name:        "Mikhail Bulgakov",
		Biography:   "Russian writer and physician whose surreal satires were largely suppressed during the Soviet era.",
		BirthDate:   "1891-05-15",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "The Master and Margarita",
				PublishedYear: 1967,
				Pages:         412,
				Language:      "English",
				Genre:         "Magical Realism",
				Publisher:     "YMCA Press",
				Description:   "The devil arrives in 1930s Moscow, mingling with Pilate, a writer and his beloved.",
			},
		},
	},
	{
		Name:        "Vladimir Nabokov",
		Biography:   "Russian-American novelist celebrated for his stylistic virtuosity and inventive structures.",
		BirthDate:   "1899-04-22",
		Nationality: "Russian-American",
		Books: []SeedBook{
			{
				Title:         "Lolita",
				PublishedYear: 1955,
				Pages:         336,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "Olympia Press",
				Description:   "A literary professor's destructive obsession with his twelve-year-old stepdaughter.",
			},
			{
				Title:         "Pale Fire",
				PublishedYear: 1962,
				Pages:         315,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "G. P. Putnam's Sons",
				Description:   "A long poem and its unhinged commentary form a novel of mirrors and madness.",
			},
		},
	},
	{
		Name:        "Boris Pasternak",
		Biography:   "Russian poet and novelist, awarded the Nobel Prize in Literature in 1958.",
		BirthDate:   "1890-02-10",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "Doctor Zhivago",
				PublishedYear: 1957,
				Pages:         592,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "Feltrinelli",
				Description:   "A doctor and poet is swept up in love and the upheaval of the Russian Revolution.",
			},
		},
	},
	{
		Name:        "Aleksandr Solzhenitsyn",
		Biography:   "Russian novelist and historian who exposed the Soviet labour camp system through his fiction and reportage.",
		BirthDate:   "1918-12-11",
		Nationality: "Russian",
		Books: []SeedBook{
			{
				Title:         "One Day in the Life of Ivan Denisovich",
				PublishedYear: 1962,
				Pages:         178,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "Novy Mir",
				Description:   "A single day in a Soviet gulag camp told through the eyes of one prisoner.",
			},
			{
				Title:         "Cancer Ward",
				PublishedYear: 1968,
				Pages:         536,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "The Bodley Head",
				Description:   "Patients on a Soviet hospital ward confront illness, ideology and mortality together.",
			},
		},
	},
	{
		Name:        "Hermann Hesse",
		Biography:   "German-Swiss novelist and Nobel laureate whose works explore the search for self-knowledge and spirituality.",
		BirthDate:   "1877-07-02",
		Nationality: "German-Swiss",
		Books: []SeedBook{
			{
				Title:         "Steppenwolf",
				PublishedYear: 1927,
				Pages:         218,
				Language:      "English",
				Genre:         "Philosophical Fiction",
				Publisher:     "S. Fischer Verlag",
				Description:   "A solitary intellectual confronts his dual nature as both man and wolf of the steppes.",
			},
			{
				Title:         "Siddhartha",
				PublishedYear: 1922,
				Pages:         152,
				Language:      "English",
				Genre:         "Philosophical Fiction",
				Publisher:     "S. Fischer Verlag",
				Description:   "A young Brahmin's spiritual journey through wealth, asceticism and enlightenment in ancient India.",
			},
			{
				Title:         "The Glass Bead Game",
				PublishedYear: 1943,
				Pages:         558,
				Language:      "English",
				Genre:         "Philosophical Fiction",
				Publisher:     "Fretz & Wasmuth",
				Description:   "In a future intellectual utopia, a master of an abstract game questions his order's purpose.",
			},
		},
	},
	{
		Name:        "Thomas Mann",
		Biography:   "German novelist and Nobel laureate whose novels examine the inner life of the artist and bourgeois Europe.",
		BirthDate:   "1875-06-06",
		Nationality: "German",
		Books: []SeedBook{
			{
				Title:         "The Magic Mountain",
				PublishedYear: 1924,
				Pages:         706,
				Language:      "English",
				Genre:         "Philosophical Fiction",
				Publisher:     "S. Fischer Verlag",
				Description:   "A young man visits a Swiss tuberculosis sanatorium and stays for seven transformative years.",
			},
			{
				Title:         "Buddenbrooks",
				PublishedYear: 1901,
				Pages:         736,
				Language:      "English",
				Genre:         "Family Saga",
				Publisher:     "S. Fischer Verlag",
				Description:   "Four generations of a wealthy north-German merchant family slowly decline.",
			},
			{
				Title:         "Death in Venice",
				PublishedYear: 1912,
				Pages:         142,
				Language:      "English",
				Genre:         "Novella",
				Publisher:     "S. Fischer Verlag",
				Description:   "An aging writer becomes consumed by his obsession with a beautiful boy on a Venetian holiday.",
			},
		},
	},
	{
		Name:        "Johann Wolfgang von Goethe",
		Biography:   "German poet, playwright and statesman, a towering figure of European Romanticism.",
		BirthDate:   "1749-08-28",
		Nationality: "German",
		Books: []SeedBook{
			{
				Title:         "Faust",
				PublishedYear: 1808,
				Pages:         448,
				Language:      "English",
				Genre:         "Drama",
				Publisher:     "J. G. Cotta",
				Description:   "A discontented scholar makes a pact with the devil for unlimited knowledge and pleasure.",
			},
			{
				Title:         "The Sorrows of Young Werther",
				PublishedYear: 1774,
				Pages:         144,
				Language:      "English",
				Genre:         "Romance",
				Publisher:     "Weygand'sche Buchhandlung",
				Description:   "A sensitive young artist's letters chronicle his hopeless love for an engaged woman.",
			},
		},
	},
	{
		Name:        "Charlotte Brontë",
		Biography:   "English novelist and poet, eldest of the three Brontë sisters whose novels are classics of English literature.",
		BirthDate:   "1816-04-21",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Jane Eyre",
				PublishedYear: 1847,
				Pages:         532,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Smith, Elder & Co.",
				Description:   "An orphaned governess falls for the brooding master of Thornfield Hall and his terrible secret.",
			},
			{
				Title:         "Villette",
				PublishedYear: 1853,
				Pages:         656,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Smith, Elder & Co.",
				Description:   "A reserved young Englishwoman teaches at a girls' school in a fictional Belgian city.",
			},
		},
	},
	{
		Name:        "Emily Brontë",
		Biography:   "English novelist and poet, best known for her single, ferocious novel.",
		BirthDate:   "1818-07-30",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Wuthering Heights",
				PublishedYear: 1847,
				Pages:         416,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Thomas Cautley Newby",
				Description:   "A doomed love between Heathcliff and Catherine destroys two families on the Yorkshire moors.",
			},
		},
	},
	{
		Name:        "Mary Shelley",
		Biography:   "English novelist who wrote the first modern science-fiction novel at the age of nineteen.",
		BirthDate:   "1797-08-30",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Frankenstein",
				PublishedYear: 1818,
				Pages:         280,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Lackington, Hughes, Harding, Mavor & Jones",
				Description:   "A young scientist creates a sentient being from corpses and is destroyed by his creation.",
			},
		},
	},
	{
		Name:        "Bram Stoker",
		Biography:   "Irish author best known for the gothic horror novel that defined the modern vampire myth.",
		BirthDate:   "1847-11-08",
		Nationality: "Irish",
		Books: []SeedBook{
			{
				Title:         "Dracula",
				PublishedYear: 1897,
				Pages:         418,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Archibald Constable and Company",
				Description:   "A Transylvanian count travels to England in pursuit of new prey and is hunted in turn.",
			},
		},
	},
	{
		Name:        "Oscar Wilde",
		Biography:   "Irish poet and playwright known for his epigrammatic wit and aestheticism.",
		BirthDate:   "1854-10-16",
		Nationality: "Irish",
		Books: []SeedBook{
			{
				Title:         "The Picture of Dorian Gray",
				PublishedYear: 1890,
				Pages:         254,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Lippincott's Monthly Magazine",
				Description:   "A beautiful young man stays youthful while his portrait records the depravity of his soul.",
			},
			{
				Title:         "The Importance of Being Earnest",
				PublishedYear: 1895,
				Pages:         76,
				Language:      "English",
				Genre:         "Drama",
				Publisher:     "Leonard Smithers and Company",
				Description:   "Two young men maintain fictitious identities to escape social obligations and pursue romance.",
			},
		},
	},
	{
		Name:        "H.G. Wells",
		Biography:   "English writer often called the father of science fiction.",
		BirthDate:   "1866-09-21",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "The Time Machine",
				PublishedYear: 1895,
				Pages:         118,
				Language:      "English",
				Genre:         "Science Fiction",
				Publisher:     "William Heinemann",
				Description:   "A Victorian inventor travels to the year 802,701 and finds humanity divided into two species.",
			},
			{
				Title:         "The War of the Worlds",
				PublishedYear: 1898,
				Pages:         192,
				Language:      "English",
				Genre:         "Science Fiction",
				Publisher:     "William Heinemann",
				Description:   "Martian invaders devastate Victorian England with weapons of overwhelming power.",
			},
			{
				Title:         "The Invisible Man",
				PublishedYear: 1897,
				Pages:         167,
				Language:      "English",
				Genre:         "Science Fiction",
				Publisher:     "C. Arthur Pearson Ltd.",
				Description:   "A scientist discovers invisibility and slowly descends into terror and madness.",
			},
		},
	},
	{
		Name:        "Jules Verne",
		Biography:   "French novelist whose adventure stories pioneered the genre of science fiction.",
		BirthDate:   "1828-02-08",
		Nationality: "French",
		Books: []SeedBook{
			{
				Title:         "Twenty Thousand Leagues Under the Sea",
				PublishedYear: 1870,
				Pages:         452,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Pierre-Jules Hetzel",
				Description:   "Captain Nemo's submarine Nautilus carries reluctant guests on a tour of the world's oceans.",
			},
			{
				Title:         "Journey to the Center of the Earth",
				PublishedYear: 1864,
				Pages:         256,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Pierre-Jules Hetzel",
				Description:   "A German professor follows an old manuscript into a volcano in search of the planet's interior.",
			},
			{
				Title:         "Around the World in Eighty Days",
				PublishedYear: 1872,
				Pages:         242,
				Language:      "English",
				Genre:         "Adventure",
				Publisher:     "Pierre-Jules Hetzel",
				Description:   "A Victorian gentleman bets his fortune that he can circumnavigate the globe in eighty days.",
			},
		},
	},
	{
		Name:        "Joseph Conrad",
		Biography:   "Polish-British novelist who wrote in English about morality, colonialism and the sea.",
		BirthDate:   "1857-12-03",
		Nationality: "Polish-British",
		Books: []SeedBook{
			{
				Title:         "Heart of Darkness",
				PublishedYear: 1899,
				Pages:         96,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "Blackwood's Magazine",
				Description:   "A steamboat captain travels deep into the Congo to find the enigmatic ivory trader Kurtz.",
			},
			{
				Title:         "Lord Jim",
				PublishedYear: 1900,
				Pages:         313,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "William Blackwood and Sons",
				Description:   "A young British seaman's act of cowardice haunts him through years of self-imposed exile.",
			},
		},
	},
	{
		Name:        "Thomas Hardy",
		Biography:   "English novelist and poet whose tragic novels are set in the rural region he called Wessex.",
		BirthDate:   "1840-06-02",
		Nationality: "British",
		Books: []SeedBook{
			{
				Title:         "Tess of the d'Urbervilles",
				PublishedYear: 1891,
				Pages:         518,
				Language:      "English",
				Genre:         "Tragedy",
				Publisher:     "James R. Osgood, McIlvaine & Co.",
				Description:   "A poor country girl's life is ruined by a predatory cousin and a society quick to condemn her.",
			},
			{
				Title:         "Jude the Obscure",
				PublishedYear: 1895,
				Pages:         488,
				Language:      "English",
				Genre:         "Tragedy",
				Publisher:     "Osgood, McIlvaine & Co.",
				Description:   "A self-taught stonemason's dreams of scholarship and love are crushed by Victorian convention.",
			},
		},
	},
	{
		Name:        "Henry James",
		Biography:   "American-British novelist regarded as a key transitional figure between literary realism and modernism.",
		BirthDate:   "1843-04-15",
		Nationality: "American-British",
		Books: []SeedBook{
			{
				Title:         "The Portrait of a Lady",
				PublishedYear: 1881,
				Pages:         640,
				Language:      "English",
				Genre:         "Literary Fiction",
				Publisher:     "Macmillan and Co.",
				Description:   "A spirited young American heiress in Europe is drawn into a calculated and cruel marriage.",
			},
			{
				Title:         "The Turn of the Screw",
				PublishedYear: 1898,
				Pages:         128,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "William Heinemann",
				Description:   "A new governess at an isolated estate becomes convinced its children are haunted.",
			},
		},
	},
	{
		Name:        "Edgar Allan Poe",
		Biography:   "American writer, poet and critic, a central figure of American Romanticism and pioneer of detective fiction.",
		BirthDate:   "1809-01-19",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Fall of the House of Usher and Other Tales",
				PublishedYear: 1839,
				Pages:         148,
				Language:      "English",
				Genre:         "Gothic Fiction",
				Publisher:     "Burton's Gentleman's Magazine",
				Description:   "A collection of macabre tales of madness, decay and dread.",
			},
		},
	},
	{
		Name:        "Nathaniel Hawthorne",
		Biography:   "American novelist whose works often examine themes of guilt, sin and moral hypocrisy in Puritan New England.",
		BirthDate:   "1804-07-04",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Scarlet Letter",
				PublishedYear: 1850,
				Pages:         279,
				Language:      "English",
				Genre:         "Historical Fiction",
				Publisher:     "Ticknor, Reed & Fields",
				Description:   "Hester Prynne is forced to wear a scarlet 'A' for adultery in 17th-century Puritan Boston.",
			},
		},
	},
	{
		Name:        "John Steinbeck",
		Biography:   "American novelist and Nobel laureate whose works portrayed the lives of working-class Americans during the Great Depression.",
		BirthDate:   "1902-02-27",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Grapes of Wrath",
				PublishedYear: 1939,
				Pages:         464,
				Language:      "English",
				Genre:         "Realist Fiction",
				Publisher:     "The Viking Press",
				Description:   "An Oklahoma family flees the Dust Bowl for the promise of work in California.",
			},
			{
				Title:         "Of Mice and Men",
				PublishedYear: 1937,
				Pages:         107,
				Language:      "English",
				Genre:         "Novella",
				Publisher:     "Covici Friede",
				Description:   "Two displaced ranch workers cling to a shared dream of owning a small farm.",
			},
			{
				Title:         "East of Eden",
				PublishedYear: 1952,
				Pages:         601,
				Language:      "English",
				Genre:         "Family Saga",
				Publisher:     "The Viking Press",
				Description:   "Two California families retell the Cain and Abel story across generations.",
			},
		},
	},
	{
		Name:        "William Faulkner",
		Biography:   "American novelist and Nobel laureate, a leading voice of Southern literature.",
		BirthDate:   "1897-09-25",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Sound and the Fury",
				PublishedYear: 1929,
				Pages:         326,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Jonathan Cape and Harrison Smith",
				Description:   "Four perspectives reconstruct the decline of a once-prominent Mississippi family.",
			},
			{
				Title:         "As I Lay Dying",
				PublishedYear: 1930,
				Pages:         261,
				Language:      "English",
				Genre:         "Modernist Fiction",
				Publisher:     "Jonathan Cape and Harrison Smith",
				Description:   "A poor Mississippi family carries their mother's coffin across the county to bury her.",
			},
		},
	},
	{
		Name:        "Harper Lee",
		Biography:   "American novelist whose only published novel for decades became a touchstone of American literature.",
		BirthDate:   "1926-04-28",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "To Kill a Mockingbird",
				PublishedYear: 1960,
				Pages:         281,
				Language:      "English",
				Genre:         "Bildungsroman",
				Publisher:     "J. B. Lippincott & Co.",
				Description:   "Atticus Finch defends a Black man falsely accused in the segregated American South.",
			},
		},
	},
	{
		Name:        "J.D. Salinger",
		Biography:   "American writer whose reclusive life matched the alienation of his most famous protagonist.",
		BirthDate:   "1919-01-01",
		Nationality: "American",
		Books: []SeedBook{
			{
				Title:         "The Catcher in the Rye",
				PublishedYear: 1951,
				Pages:         277,
				Language:      "English",
				Genre:         "Bildungsroman",
				Publisher:     "Little, Brown and Company",
				Description:   "Holden Caulfield wanders New York after his expulsion from prep school.",
			},
		},
	},
}
