// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: author.queries.sql

package repositories

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuthor = `-- name: CreateAuthor :exec
;

INSERT INTO authors (
    id,
    name,
    biography,
    birth_date,
    nationality,
    image
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateAuthorParams struct {
	ID          uuid.UUID
	Name        string
	Biography   string
	BirthDate   time.Time
	Nationality string
	Image       sql.NullString
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, createAuthor,
		arg.ID,
		arg.Name,
		arg.Biography,
		arg.BirthDate,
		arg.Nationality,
		arg.Image,
	)
	return err
}

const deleteAuthorById = `-- name: DeleteAuthorById :exec
;

delete from authors
where id = ?
`

func (q *Queries) DeleteAuthorById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAuthorById, id)
	return err
}

const getAuthorById = `-- name: GetAuthorById :one
;

select id, name, biography, birth_date, nationality, image, created_at, updated_at
from authors
where id = ?
`

func (q *Queries) GetAuthorById(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorById, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		&i.BirthDate,
		&i.Nationality,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
;

select id, name, biography, birth_date, nationality, image, created_at, updated_at
from authors
where name = ?
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		&i.BirthDate,
		&i.Nationality,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthors = `-- name: GetAuthors :many
select id, name, biography, birth_date, nationality, image, created_at, updated_at
from authors
limit ?
offset ?
`

type GetAuthorsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetAuthors(ctx context.Context, arg GetAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Biography,
			&i.BirthDate,
			&i.Nationality,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorsCount = `-- name: GetAuthorsCount :one
select count(*)
from authors
`

func (q *Queries) GetAuthorsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAuthorsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors SET 
    name = COALESCE(?1, name),
    biography = COALESCE(?2, biography),
    birth_date = COALESCE(?3, birth_date),
    nationality = COALESCE(?4, nationality),
    image = COALESCE(?5, image)
WHERE
    id = ?6
RETURNING
    id, name, biography, birth_date, nationality, image, created_at, updated_at
`

type UpdateAuthorParams struct {
	Name        sql.NullString
	Biography   sql.NullString
	BirthDate   sql.NullTime
	Nationality sql.NullString
	Image       sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, updateAuthor,
		arg.Name,
		arg.Biography,
		arg.BirthDate,
		arg.Nationality,
		arg.Image,
		arg.ID,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		&i.BirthDate,
		&i.Nationality,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
