// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book.queries.sql

package repositories

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :exec
;

INSERT INTO books (
    id,
    title,
    author_id,
    isbn,
    publisher,
    published_date,
    pages,
    language,
    genre,
    description
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateBookParams struct {
	ID            uuid.UUID
	Title         string
	AuthorID      uuid.UUID
	Isbn          string
	Publisher     sql.NullString
	PublishedDate time.Time
	Pages         sql.NullInt64
	Language      sql.NullString
	Genre         sql.NullString
	Description   sql.NullString
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) error {
	_, err := q.db.ExecContext(ctx, createBook,
		arg.ID,
		arg.Title,
		arg.AuthorID,
		arg.Isbn,
		arg.Publisher,
		arg.PublishedDate,
		arg.Pages,
		arg.Language,
		arg.Genre,
		arg.Description,
	)
	return err
}

const deleteBook = `-- name: DeleteBook :exec
delete from books
where id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBookById = `-- name: GetBookById :one
;

select id, title, author_id, isbn, publisher, published_date, pages, language, genre, description, created_at, updated_at
from books
where id = ?
`

func (q *Queries) GetBookById(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookById, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Publisher,
		&i.PublishedDate,
		&i.Pages,
		&i.Language,
		&i.Genre,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByIsbn = `-- name: GetBookByIsbn :one
;

select id, title, author_id, isbn, publisher, published_date, pages, language, genre, description, created_at, updated_at
from books
where isbn = ?
`

func (q *Queries) GetBookByIsbn(ctx context.Context, isbn string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByIsbn, isbn)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Publisher,
		&i.PublishedDate,
		&i.Pages,
		&i.Language,
		&i.Genre,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooks = `-- name: GetBooks :many
select id, title, author_id, isbn, publisher, published_date, pages, language, genre, description, created_at, updated_at
from books
limit ?
offset ?
`

type GetBooksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetBooks(ctx context.Context, arg GetBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Isbn,
			&i.Publisher,
			&i.PublishedDate,
			&i.Pages,
			&i.Language,
			&i.Genre,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
;

select id, title, author_id, isbn, publisher, published_date, pages, language, genre, description, created_at, updated_at
from books
where author_id = ?
limit ?
offset ?
`

type GetBooksByAuthorParams struct {
	AuthorID uuid.UUID
	Limit    int64
	Offset   int64
}

func (q *Queries) GetBooksByAuthor(ctx context.Context, arg GetBooksByAuthorParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Isbn,
			&i.Publisher,
			&i.PublishedDate,
			&i.Pages,
			&i.Language,
			&i.Genre,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksCount = `-- name: GetBooksCount :one
;

select count(*)
from books
`

func (q *Queries) GetBooksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBooksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBooksCountByAuthor = `-- name: GetBooksCountByAuthor :one
;

select count(*)
from books
where author_id = ?
`

func (q *Queries) GetBooksCountByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBooksCountByAuthor, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateBook = `-- name: UpdateBook :one
UPDATE books SET 
    title = COALESCE(?1, title),
    isbn = COALESCE(?2, isbn),
    publisher = COALESCE(?3, publisher),
    published_date = COALESCE(?4, published_date),
    pages = COALESCE(?5, pages),
    language = COALESCE(?6, language),
    genre = COALESCE(?7, genre),
    description = COALESCE(?8, description)
WHERE
    id = ?9
RETURNING
    id, title, author_id, isbn, publisher, published_date, pages, language, genre, description, created_at, updated_at
`

type UpdateBookParams struct {
	Title         sql.NullString
	Isbn          sql.NullString
	Publisher     sql.NullString
	PublishedDate sql.NullTime
	Pages         sql.NullInt64
	Language      sql.NullString
	Genre         sql.NullString
	Description   sql.NullString
	ID            uuid.UUID
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.Title,
		arg.Isbn,
		arg.Publisher,
		arg.PublishedDate,
		arg.Pages,
		arg.Language,
		arg.Genre,
		arg.Description,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Publisher,
		&i.PublishedDate,
		&i.Pages,
		&i.Language,
		&i.Genre,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
