// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repositories

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID          uuid.UUID
	Name        string
	Biography   string
	BirthDate   time.Time
	Nationality string
	Image       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Book struct {
	ID            uuid.UUID
	Title         string
	AuthorID      uuid.UUID
	Isbn          string
	Publisher     sql.NullString
	PublishedDate time.Time
	Pages         sql.NullInt64
	Language      sql.NullString
	Genre         sql.NullString
	Description   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
